application:
    container_name: application
    build: code
    volumes:
        - ../bds-manager:/var/www/bds-manager
        - ../logs/bds-manager:/var/www/bds-manager/var/logs
db:
    container_name: db
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=bds-manager"
        - "MYSQL_PASSWORD=bds-manager"
        - "MYSQL_DATABASE=bds-manager"
web:
    container_name: web
    build: apache-php
    links:
        - db
    ports:
        - 80:80
    volumes_from:
        - application

elk:
    container_name: elk
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./elk/logstash:/etc/logstash
        - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - web